USE EscuelaXYZ;
GO
DROP PROCEDURE IF EXISTS XYZ_SP_API_ALUMNOS_SEL;
GO
CREATE PROCEDURE XYZ_SP_API_ALUMNOS_SEL
AS
BEGIN
	SELECT
		A.IN_ID_ALUMNO,
		A.IN_ID_AULA,
		A.VC_NOMBRES,
		A.VC_APELLIDOS,
		AU.VC_ETAPA,
		AU.CH_GRADO,
		AU.CH_SECCION
	FROM XYZ_TA_ALUMNO A
	INNER JOIN XYZ_TA_AULA AU ON AU.IN_ID_AULA = A.IN_ID_AULA
	WHERE A.CH_ESTADO = 'A'
	AND AU.CH_ESTADO = 'A'
END;