USE EscuelaXYZ;
GO
DROP PROCEDURE IF EXISTS XYZ_SP_API_ALUMNO_INS;
GO
CREATE PROCEDURE XYZ_SP_API_ALUMNO_INS
	@PARAM_VC_NOMBRES VARCHAR(50),
	@PARAM_VC_APELLIDOS VARCHAR(50)
AS
BEGIN
	INSERT INTO XYZ_TA_ALUMNO (IN_ID_AULA, VC_NOMBRES, VC_APELLIDOS, CH_ESTADO)
	VALUES (0, @PARAM_VC_NOMBRES, @PARAM_VC_APELLIDOS, 'A')

	SELECT 'Se creo el alumno correctamente' AS VC_MENSAJE
END;