USE EscuelaXYZ;
GO
DROP PROCEDURE IF EXISTS XYZ_SP_API_DOCENTE_ALUMNOS_SEL;
GO
CREATE PROCEDURE XYZ_SP_API_DOCENTE_ALUMNOS_SEL
	@PARAM_IN_ID_DOCENTE INT
AS
BEGIN
	SELECT
		A.IN_ID_ALUMNO,
		A.VC_NOMBRES,
		A.VC_APELLIDOS,
		AU.CH_GRADO,
		AU.CH_SECCION
	FROM XYZ_TA_ALUMNO A
	INNER JOIN XYZ_TA_AULA AU ON AU.IN_ID_AULA = A.IN_ID_AULA
	INNER JOIN XYZ_TA_DOCENTE D ON D.IN_ID_AULA = AU.IN_ID_AULA
	WHERE D.IN_ID_DOCENTE = @PARAM_IN_ID_DOCENTE
	AND A.CH_ESTADO = 'A'
	AND AU.CH_ESTADO = 'A'
	AND D.CH_ESTADO = 'A'
END;