USE EscuelaXYZ;
GO
DROP PROCEDURE IF EXISTS XYZ_SP_API_ASIGNAR_ALUMNO_AULA;
GO
CREATE PROCEDURE XYZ_SP_API_ASIGNAR_ALUMNO_AULA
	@PARAM_IN_ID_AULA INT,
	@PARAM_IN_ID_ALUMNO INT
AS
BEGIN
	DECLARE @CantidadAlumnos INT

	SET @CantidadAlumnos = (SELECT COUNT(A.IN_ID_ALUMNO) FROM XYZ_TA_ALUMNO A WHERE A.IN_ID_AULA = @PARAM_IN_ID_AULA)

	IF @CantidadAlumnos >= 5
	BEGIN
		SELECT 'Se ha alcanzado el límite de alumnos por aula' AS VC_MENSAJE
	END
	ELSE
	BEGIN
		UPDATE XYZ_TA_ALUMNO SET IN_ID_AULA = @PARAM_IN_ID_AULA
		WHERE IN_ID_ALUMNO = @PARAM_IN_ID_ALUMNO

		SELECT 'Se ha añadido el alumno correctamente' AS VC_MENSAJE
	END
END;