USE EscuelaXYZ;
GO
DROP TABLE IF EXISTS XYZ_TA_ALUMNO;
CREATE TABLE XYZ_TA_ALUMNO
(
    IN_ID_ALUMNO INT IDENTITY(1,1) PRIMARY KEY,
	IN_ID_AULA INT,
	VC_NOMBRES VARCHAR(50),
    VC_APELLIDOS VARCHAR(50),
	CH_ESTADO CHAR(1)
);